services:
  server:
    image: afoley587/coding-challenges/grpc-golang:latest
    build:
      context: .
    command:
      - server
      - run
      - --addr
      - 0.0.0.0:9090
      - --redis-address
      - redis:6379
    ports:
      - 9090:9090
  redis:
    image: redis:latest
